apiVersion: 1

datasources:
  - name: Prometheus Local
    type: prometheus
    uid: prometheus_local
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
